java_binary (
    name = "runner",
    srcs = glob(["runner/**/*.java"]),
    main_class = "com.example.ProjectRunner",
    deps = [":greeter"],
)

java_library (
    name = "greeter",
    srcs = glob(["greeter/**/*.java"]),
)